# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      Greeting: Hello
      ProjectImageName: action-test:$GITHUB_SHA

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # - name: Run app
      #   run: |
      #     cd $GITHUB_WORKSPACE
      #     go run main.go &

      # - name: Process status check
      #   run: ps -ef|grep main

      # - name: Curl /ping
      #   run: curl localhost:9090/ping

      - name: Print env var
        run: |
          echo $CI
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_SHA
          echo $GITHUB_REF_NAME

      - name: Set env var
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env: 
          First_Name: Mona

      - name: Say hello in another step
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"

      - name: Echo project image name
        run: echo $ProjectImageName

      - name: Set image tag
        run: echo "IMAGE_TAG=action-test:$(date '+%Y%m%d-%H%M%S')-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Echo image tag
        run: echo $IMAGE_TAG
      